[tool.poetry]
name = "shopify-backend"
version = "0.1.0"
description = ""
authors = [
     "Ankit Shrestha <ankit.shrestha196@gmail.com>"
]

readme = "README.md"

packages = [
    {include="shopify_backend", from="src"}
]

[tool.poetry.dependencies]
python = "^3.12"
fire = "^0.7.1"
fastapi = "^0.135.2"
uvicorn = "^0.42.0"
openai = "^2.30.0"
pydantic-settings = "^2.13.1"
pyaml = "^26.2.1"
loguru = "^0.7.3"


[tool.poetry.scripts]
cli="cli.web_cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
